//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\marius.wodtke\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://crm543863.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"CrmEarlyBound" /out:"C:\Users\marius.wodtke\source\repos\Kunter-Bunt\D365GenericConfiguration\Source\GenericConfiguration\mwo.GenericConfiguration.Plugins\Models\CRM\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"admin@CRM543863.onmicrosoft.com" /password:"**********" 
//------------------------------------------------------------------------------

namespace mwo.GenericConfiguration.Plugins.Models.CRM
{


	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum mwo_GenericConfiguration_mwo_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Boolean = 122870003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CommaseparatedList = 122870005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JSON = 122870001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Number = 122870004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SemicolonseparatedList = 122870006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unspecified = 122870000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		XML = 122870002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum mwo_GenericConfiguration_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum msdyn_msdyn_requirementrelationship_msdyn_resourcegroupings
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationalUnit = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelatedResourcePools = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Location = 192350002,
	}
}
